# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  database: testnet1_collectd
  url: http://influxdb:8086
  isDefault: false
  editable: true
