---

- name: Install Docker package
  become: yes
  package:
    name: docker.io
    state: present

- name: Create {{ metrics_user }} user
  become: yes
  user:
    name: "{{ metrics_user }}"
    create_home: no
    groups: docker, lxd

- name: Create {{ metrics_checkout_dir }}
  become: yes
  file:
    path: "{{ metrics_checkout_dir }}"
    state: directory
    group: "{{ deployers_group }}"
    mode: u=rwx,g=rwx,o=r

- name: Checkout runtime files
  git:
    repo: 'https://github.com/rchain/rtestnet-monitoring.git'
    clone: yes
    update: yes
    force: yes
    dest: "{{ metrics_checkout_dir }}"
    version: "{{ metrics_checkout_commit }}"

- name: Render metrics.service
  template:
    src: metrics.service.j2
    dest: "{{ metrics_checkout_dir }}/metrics.service"

- name: Render grafana.conf
  template:
    src: grafana.conf.j2
    dest: "{{ metrics_checkout_dir }}/grafana.conf"

- name: Fix attibutes
  become: yes
  file:
    path: "{{ metrics_checkout_dir }}"
    owner: "{{ metrics_user }}"
    recurse: yes

- name: Symlink metrics.service file
  become: yes
  file:
    src: "{{ metrics_checkout_dir }}/metrics.service"
    dest: /etc/systemd/system/metrics.service
    state: link

# Files in the directory below are created with a user id managed by docker,
# since that's a mounted volume.  I don't see how to restrict permissions just
# to that user, hence the "u=rwx,g=rwx,o=rwx" permissions.
- name: Update Grafana data directory permissions
  become: yes
  file:
    path: /var/lib/grafana
    owner: "{{ metrics_user }}"
    group: "{{ metrics_user }}"
    mode: "u=rwx,g=rwx,o=rwx"
    recurse: yes

- name: Register systemd unit
  become: yes
  systemd:
    daemon_reload: true

- name: Install Docker PIP package
  become: yes
  package:
    name: python-docker
    state: present

- name: Create docker network
  become: yes
  docker_network:
    name: perf_harness
    driver: bridge

- name: Install docker-compose package
  become: yes
  package:
    name: docker-compose
    state: present

- name: Run systemd unit at boot
  become: yes
  systemd:
    name: metrics
    enabled: yes

- name: Restart systemd service
  become: yes
  systemd:
    name: metrics
    state: restarted
